services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=USER  # Votre identifiant PIA (commence par p)
      - OPENVPN_PASSWORD=PASS 
      - SERVER_REGIONS=Israel  # Choisissez votre région (ex: France, Germany, etc.)
    ports:
      - 11470:11470 # Port de streaming de Stremio
    restart: unless-stopped

  stremio:
    image: stremio/server:latest
    container_name: stremio
    network_mode: "service:gluetun" # Tout le trafic passe par Gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - NO_CORS=1 # Recommandé pour l'utilisation avec l'interface web
    restart: unless-stopped
